[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/workers/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/css; charset=UTF-8"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/libs/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200